# Generated by Django 4.2.9 on 2024-04-04 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('USERADDRESS', models.CharField(max_length=50)),
                ('USEREMAIL', models.CharField(max_length=50)),
                ('PHONENUMBER', models.IntegerField(max_length=10)),
                ('ARTISTNAME', models.CharField(max_length=50)),
                ('ARTISTEMAIL', models.CharField(max_length=50)),
                ('ADDSERVICE', models.CharField(max_length=10)),
                ('APPOINTMENTDATE', models.DateField(default=True)),
                ('APPOINTMENTTIME', models.TimeField(default=True)),
                ('ACTION', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REASONFORCANCELLATION', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('makeupartistname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField()),
                ('complaints', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USERNAME', models.CharField(max_length=50)),
                ('PASSWORD', models.CharField(max_length=50)),
                ('STATUS', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='makeupartist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
                ('email', models.CharField(max_length=50)),
                ('license', models.FileField(upload_to='')),
                ('location', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=50)),
                ('ACTION', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('ARTISTNAME', models.CharField(max_length=50)),
                ('EMAILID', models.CharField(max_length=50)),
                ('DATE', models.DateField(default=True)),
                ('TIME', models.TimeField(default=True)),
                ('AMOUNT', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('addservice', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=50)),
                ('AGE', models.IntegerField()),
                ('USERNAME', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('EMAIL', models.CharField(max_length=50)),
                ('PHONENUMBER', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beautyapp.user')),
            ],
        ),
    ]
