# Generated by Django 4.2.9 on 2024-04-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='STATUS',
            field=models.IntegerField(default=2),
        ),
    ]
