# Generated by Django 4.2.9 on 2024-04-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0002_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='USERNAME',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
