# Generated by Django 4.2.9 on 2024-04-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0003_booking_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='PHONENUMBER',
            field=models.IntegerField(),
        ),
    ]
