# Generated by Django 4.2.9 on 2024-04-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0004_alter_booking_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='adpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=60)),
                ('amount', models.IntegerField()),
                ('date', models.DateField(default=True)),
                ('artistname', models.CharField(max_length=50)),
            ],
        ),
    ]
