# Generated by Django 5.0.4 on 2024-04-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0005_adpay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='ARTISTEMAIL',
            new_name='EMAIL',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ARTISTNAME',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='USERADDRESS',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='USEREMAIL',
        ),
    ]
