# Generated by Django 5.0.4 on 2024-04-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0006_rename_artistemail_booking_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=60)),
                ('phone_num', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('beautyparlour_name', models.CharField(max_length=30)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('service', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='ARTISTNAME',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
