# Generated by Django 5.0.4 on 2024-04-22 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0007_appointment_booking_artistname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='beautyparlour_name',
            new_name='artistname',
        ),
    ]
