# Generated by Django 5.0.4 on 2024-04-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0008_rename_beautyparlour_name_appointment_artistname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(max_length=20),
        ),
    ]
