# Generated by Django 5.0.4 on 2024-05-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0011_alter_appointment_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complaint',
            new_name='complaints',
        ),
    ]
