# Generated by Django 5.0.4 on 2024-05-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0012_rename_complaint_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('makeupartistname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.IntegerField()),
                ('complaint', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='complaints',
        ),
    ]
