# Generated by Django 5.0.4 on 2024-05-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0013_complaint_delete_complaints'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='complaint',
            new_name='comp',
        ),
    ]
