# Generated by Django 5.0.6 on 2024-05-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0016_complaint_delete_comp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaints',
            new_name='comp',
        ),
    ]
