# Generated by Django 5.0.6 on 2024-06-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0017_rename_complaints_complaint_comp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='DATE',
            field=models.DateField(),
        ),
    ]
