# Generated by Django 5.0.6 on 2024-06-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0018_alter_payments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_date',
            field=models.DateField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booking_time',
            field=models.TimeField(default=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='DATE',
            field=models.DateField(default=True),
        ),
    ]
