# Generated by Django 5.0.6 on 2024-06-10 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0019_alter_appointment_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='DATE',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
