# Generated by Django 5.0.6 on 2024-06-13 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0020_alter_payments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adpay',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booking_time',
            field=models.TimeField(),
        ),
    ]
