# Generated by Django 5.0.6 on 2024-06-13 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0022_alter_appointment_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booking_time',
            field=models.TimeField(),
        ),
    ]
