# Generated by Django 5.0.6 on 2024-06-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0023_alter_appointment_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
