# Generated by Django 5.0.6 on 2024-07-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0025_alter_appointment_booking_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artistname', models.CharField(max_length=30)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
