# Generated by Django 5.0.6 on 2024-08-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyapp', '0026_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='addservice',
            field=models.CharField(max_length=500),
        ),
    ]
